---
- name: install software
  hosts: all
  vars:
    packages:
       - name: nginx
         required: True
       - name: mysql
         required: True
       - name: apache
         required: False


    tasks:
    - name: Install "{{ item.name }}" on debian
      apt:
        name: "{{ item.name }}"
        state: present


      loop: "{{ packages }}"
