name: Employee Application CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: mvn clean package

      - name: Run tests
        run: mvn test

      - name: Build Docker image
        run: |
          docker build \
            -t employee-app:${{ github.sha }} .

      # AWS authentication
      # ECR login
      # Docker push
      # EKS deployment
